name: GitHub Actions Demo

# This is the trigger
on:
    workflow_dispatch:

# This is the job
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Triggered by ${{ github.event_name }}"
            - uses: actions/checkout@v4
            - run: |
                echo "Contents of the repo called ${{ github.repository }}"
                tree
    Carlos:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Another machine :)"