name: Fetch data from favorite author

on:
  workflow_dispatch:
  schedule:
  - cron: "0 8 * * *"

jobs:
  get-author-data:
    name: Get Author Data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make directory if not exists
        run: mkdir -p ex01/data/
      - name: Remove previous file
        run: rm -f ex01/data/authors.json
      - name: Fetch data and save to file
        run: curl https://openlibrary.org/search/authors.json?q=${{ secrets.MY_AUTHOR }} > ex01/data/author.json
      - name: Add and push new files
        run: |
          git config --global user.email "eloisanchez16@gmail.com"
          git config --global user.name EloiSanchez
          git add ex01/data/author.json
          git commit -m "Add new file from action"
          git push
